# Introduction To Data Analysis

- Asking the right questions and extracting meaning from raw numbers

# Loading Data & First Inspection

- Pandas basics, reading CSV, head(), info(), describe()

## Key Concepts
- **Pandas DataFrame** - a two-dimensional table with labeled rows and columns.
- **Series** - a single column of data.
- **Import** - bringing a library into Python sesssion.
- **Read CSV** - `pandas.read_csv()` converts a text file with commans into a DataFrame.

### Step 1: Set up environment

```
# install pandas using command prompt
pip install pandas numpy

# install in Jupyter Notebook
!pip install pandas numpy

# conda installation
conda install pandas numpy
```

In [3]:
# After installation, import the libraries
import pandas as pd
import numpy as np

In [4]:
print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

Pandas version: 2.2.1
Numpy version: 1.23.5

### Step 2: Load the dataset

In [6]:
# Place the movies-new.csv file in the same folder as the notebook.
# Load the csv file.

In [7]:
pd.read_csv("movies-new.csv")

,Rank,Title,Studio,Gross,Year,Budget,Runtime,Genre,Director,Actors,...,Awards,Sequel,Franchise,Profit,ROI,ReleaseMonth,ReleaseDayOfWeek,Age,ProductionCountries,WeekendGross
0,1,Avengers: Endgame,Buena Vista,"$2,796.30",2019,356000000.0,181.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Evans, Mark Ruffalo",...,Oscar for Best Visual Effects,1,Marvel,2440300000,6.85,4,Friday,7,USA,150000000
1,2,Avatar,Fox,"$2,789.70",2009,237000000.0,162.0,"Action, Adventure, Fantasy",James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver",...,Oscar for Best Cinematography,0,NaN,2522700000,10.64,12,Friday,17,USA,180000000
2,3,Titanic,Paramount,"$2,187.50",1997,200000000.0,195.0,"Drama, Romance",James Cameron,"Leonardo DiCaprio, Kate Winslet, Billy Zane",...,Oscar for Best Picture,0,NaN,1987500000,9.94,12,Friday,29,USA,120000000
3,4,Star Wars: The Force Awakens,Buena Vista,"$2,068.20",2015,245000000.0,138.0,"Action, Adventure, Sci-Fi",J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac",...,NaN,1,Star Wars,1823200000,7.44,12,Friday,11,USA,170000000
4,5,Avengers: Infinity War,BV,"$2,048.40",2018,300000000.0,149.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Hemsworth, Josh Brolin",...,NaN,1,Marvel,1748400000,5.83,4,Friday,8,USA,190000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,The Amazing Spider-Man,Sony,$757.90,2012,230000000.0,136.0,"Action, Adventure, Sci-Fi",Marc Webb,"Andrew Garfield, Emma Stone, Rhys Ifans",...,NaN,1,Spider-Man,527900000,2.30,7,Tuesday,14,USA,50000000
96,97,The Hunger Games: Mockingjay - Part 1,Lionsgate,$755.40,2014,125000000.0,123.0,"Adventure, Sci-Fi, Thriller",Francis Lawrence,"Jennifer Lawrence, Josh Hutcherson, Liam Hemsw...",...,NaN,1,Hunger Games,630400000,5.04,11,Friday,12,USA,50000000
97,98,Shrek Forever After,Dreamworks,$752.60,2010,165000000.0,93.0,"Animation, Adventure, Comedy",Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz",...,NaN,1,Shrek,587600000,3.56,5,Friday,16,USA,40000000
98,99,X-Men: Days of Future Past,Fox,$747.90,2014,200000000.0,132.0,"Action, Adventure, Sci-Fi",Bryan Singer,"Hugh Jackman, James McAvoy, Michael Fassbender",...,NaN,1,X-Men,547900000,2.74,5,Friday,12,USA,60000000
99,100,Madagascar 3: Europe's Most Wanted,Dreamworks,$746.90,2012,145000000.0,93.0,"Animation, Adventure, Comedy",Eric Darnell,"Ben Stiller, Chris Rock, David Schwimmer",...,NaN,1,Madagascar,601900000,4.15,6,Friday,14,USA,50000000

In [11]:
movies = pd.read_csv("movies-new.csv")
movies

,Rank,Title,Studio,Gross,Year,Budget,Runtime,Genre,Director,Actors,...,Awards,Sequel,Franchise,Profit,ROI,ReleaseMonth,ReleaseDayOfWeek,Age,ProductionCountries,WeekendGross
0,1,Avengers: Endgame,Buena Vista,"$2,796.30",2019,356000000.0,181.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Evans, Mark Ruffalo",...,Oscar for Best Visual Effects,1,Marvel,2440300000,6.85,4,Friday,7,USA,150000000
1,2,Avatar,Fox,"$2,789.70",2009,237000000.0,162.0,"Action, Adventure, Fantasy",James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver",...,Oscar for Best Cinematography,0,NaN,2522700000,10.64,12,Friday,17,USA,180000000
2,3,Titanic,Paramount,"$2,187.50",1997,200000000.0,195.0,"Drama, Romance",James Cameron,"Leonardo DiCaprio, Kate Winslet, Billy Zane",...,Oscar for Best Picture,0,NaN,1987500000,9.94,12,Friday,29,USA,120000000
3,4,Star Wars: The Force Awakens,Buena Vista,"$2,068.20",2015,245000000.0,138.0,"Action, Adventure, Sci-Fi",J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac",...,NaN,1,Star Wars,1823200000,7.44,12,Friday,11,USA,170000000
4,5,Avengers: Infinity War,BV,"$2,048.40",2018,300000000.0,149.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Hemsworth, Josh Brolin",...,NaN,1,Marvel,1748400000,5.83,4,Friday,8,USA,190000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,The Amazing Spider-Man,Sony,$757.90,2012,230000000.0,136.0,"Action, Adventure, Sci-Fi",Marc Webb,"Andrew Garfield, Emma Stone, Rhys Ifans",...,NaN,1,Spider-Man,527900000,2.30,7,Tuesday,14,USA,50000000
96,97,The Hunger Games: Mockingjay - Part 1,Lionsgate,$755.40,2014,125000000.0,123.0,"Adventure, Sci-Fi, Thriller",Francis Lawrence,"Jennifer Lawrence, Josh Hutcherson, Liam Hemsw...",...,NaN,1,Hunger Games,630400000,5.04,11,Friday,12,USA,50000000
97,98,Shrek Forever After,Dreamworks,$752.60,2010,165000000.0,93.0,"Animation, Adventure, Comedy",Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz",...,NaN,1,Shrek,587600000,3.56,5,Friday,16,USA,40000000
98,99,X-Men: Days of Future Past,Fox,$747.90,2014,200000000.0,132.0,"Action, Adventure, Sci-Fi",Bryan Singer,"Hugh Jackman, James McAvoy, Michael Fassbender",...,NaN,1,X-Men,547900000,2.74,5,Friday,12,USA,60000000
99,100,Madagascar 3: Europe's Most Wanted,Dreamworks,$746.90,2012,145000000.0,93.0,"Animation, Adventure, Comedy",Eric Darnell,"Ben Stiller, Chris Rock, David Schwimmer",...,NaN,1,Madagascar,601900000,4.15,6,Friday,14,USA,50000000

In [12]:
# head(n) method of dataframe to display first n rows, default value is 5

In [13]:
movies.head()

,Rank,Title,Studio,Gross,Year,Budget,Runtime,Genre,Director,Actors,...,Awards,Sequel,Franchise,Profit,ROI,ReleaseMonth,ReleaseDayOfWeek,Age,ProductionCountries,WeekendGross
0,1,Avengers: Endgame,Buena Vista,"$2,796.30",2019,356000000.0,181.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Evans, Mark Ruffalo",...,Oscar for Best Visual Effects,1,Marvel,2440300000,6.85,4,Friday,7,USA,150000000
1,2,Avatar,Fox,"$2,789.70",2009,237000000.0,162.0,"Action, Adventure, Fantasy",James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver",...,Oscar for Best Cinematography,0,NaN,2522700000,10.64,12,Friday,17,USA,180000000
2,3,Titanic,Paramount,"$2,187.50",1997,200000000.0,195.0,"Drama, Romance",James Cameron,"Leonardo DiCaprio, Kate Winslet, Billy Zane",...,Oscar for Best Picture,0,NaN,1987500000,9.94,12,Friday,29,USA,120000000
3,4,Star Wars: The Force Awakens,Buena Vista,"$2,068.20",2015,245000000.0,138.0,"Action, Adventure, Sci-Fi",J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac",...,NaN,1,Star Wars,1823200000,7.44,12,Friday,11,USA,170000000
4,5,Avengers: Infinity War,BV,"$2,048.40",2018,300000000.0,149.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Hemsworth, Josh Brolin",...,NaN,1,Marvel,1748400000,5.83,4,Friday,8,USA,190000000

In [14]:
type(movies)  # data type of the object

pandas.core.frame.DataFrame

In [15]:
movies.head(2)

,Rank,Title,Studio,Gross,Year,Budget,Runtime,Genre,Director,Actors,...,Awards,Sequel,Franchise,Profit,ROI,ReleaseMonth,ReleaseDayOfWeek,Age,ProductionCountries,WeekendGross
0,1,Avengers: Endgame,Buena Vista,"$2,796.30",2019,356000000.0,181.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Evans, Mark Ruffalo",...,Oscar for Best Visual Effects,1,Marvel,2440300000,6.85,4,Friday,7,USA,150000000
1,2,Avatar,Fox,"$2,789.70",2009,237000000.0,162.0,"Action, Adventure, Fantasy",James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver",...,Oscar for Best Cinematography,0,NaN,2522700000,10.64,12,Friday,17,USA,180000000

- **Important observation**: The 'Gross' column contains a $ sign and a trailing space - this means it is a **string**, not a number. **Data Analysis always starts with noticing such issues**.

### Step 3: Check the shape and column names

In [19]:
print("Number of rows and columns:", movies.shape)
print("\nColumn names:")
print(movies.columns.tolist())

Number of rows and columns: (100, 27)

Column names:
['Rank', 'Title', 'Studio', 'Gross', 'Year', 'Budget', 'Runtime', 'Genre', 'Director', 'Actors', 'ReleaseDate', 'Country', 'Language', 'Rating', 'Votes', 'Metascore', 'MPAA', 'Awards', 'Sequel', 'Franchise', 'Profit', 'ROI', 'ReleaseMonth', 'ReleaseDayOfWeek', 'Age', 'ProductionCountries', 'WeekendGross']

### Step 4: Get a comprehensive summary with `info()`

In [20]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rank                 100 non-null    int64
 1   Title                100 non-null    object
 2   Studio               100 non-null    object
 3   Gross                100 non-null    object
 4   Year                 100 non-null    int64
 5   Budget               99 non-null     float64
 6   Runtime              99 non-null     float64
 7   Genre                100 non-null    object
 8   Director             100 non-null    object
 9   Actors               100 non-null    object
 10  ReleaseDate          100 non-null    object
 11  Country              100 non-null    object
 12  Language             100 non-null    object
 13  Rating               99 non-null     float64
 14  Votes                100 non-null    int64
 15  Metascore            100 non-null    int64
 16  MPAA                 99 non-null     object
 17  Awards               20 non-null     object
 18  Sequel               100 non-null    int64
 19  Franchise            79 non-null     object
 20  Profit               100 non-null    int64
 21  ROI                  100 non-null    float64
 22  ReleaseMonth         100 non-null    int64
 23  ReleaseDayOfWeek     100 non-null    object
 24  Age                  100 non-null    int64
 25  ProductionCountries  100 non-null    object
 26  WeekendGross         100 non-null    int64
dtypes: float64(4), int64(9), object(14)
memory usage: 21.2+ KB