# Introduction To Data Analysis

- Asking the right questions and extracting meaning from raw numbers

# Loading Data & First Inspection

- Pandas basics, reading CSV, head(), info(), describe()

## Key Concepts
- **Pandas DataFrame** - a two-dimensional table with labeled rows and columns.
- **Series** - a single column of data.
- **Import** - bringing a library into Python sesssion.
- **Read CSV** - `pandas.read_csv()` converts a text file with commans into a DataFrame.

### Step 1: Set up environment

```
# install pandas using command prompt
pip install pandas numpy

# install in Jupyter Notebook
!pip install pandas numpy

# conda installation
conda install pandas numpy
```

In [3]:
# After installation, import the libraries
import pandas as pd
import numpy as np

In [4]:
print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

Pandas version: 2.2.1
Numpy version: 1.23.5

### Step 2: Load the dataset

In [5]:
# Place the movies-new.csv file in the same folder as the notebook.
# Load the csv file.

In [6]:
pd.read_csv("movies-new.csv")

,Rank,Title,Studio,Gross,Year,Budget,Runtime,Genre,Director,Actors,...,Awards,Sequel,Franchise,Profit,ROI,ReleaseMonth,ReleaseDayOfWeek,Age,ProductionCountries,WeekendGross
0,1,Avengers: Endgame,Buena Vista,"$2,796.30",2019,356000000.0,181.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Evans, Mark Ruffalo",...,Oscar for Best Visual Effects,1,Marvel,2440300000,6.85,4,Friday,7,USA,150000000
1,2,Avatar,Fox,"$2,789.70",2009,237000000.0,162.0,"Action, Adventure, Fantasy",James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver",...,Oscar for Best Cinematography,0,NaN,2522700000,10.64,12,Friday,17,USA,180000000
2,3,Titanic,Paramount,"$2,187.50",1997,200000000.0,195.0,"Drama, Romance",James Cameron,"Leonardo DiCaprio, Kate Winslet, Billy Zane",...,Oscar for Best Picture,0,NaN,1987500000,9.94,12,Friday,29,USA,120000000
3,4,Star Wars: The Force Awakens,Buena Vista,"$2,068.20",2015,245000000.0,138.0,"Action, Adventure, Sci-Fi",J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac",...,NaN,1,Star Wars,1823200000,7.44,12,Friday,11,USA,170000000
4,5,Avengers: Infinity War,BV,"$2,048.40",2018,300000000.0,149.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Hemsworth, Josh Brolin",...,NaN,1,Marvel,1748400000,5.83,4,Friday,8,USA,190000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,The Amazing Spider-Man,Sony,$757.90,2012,230000000.0,136.0,"Action, Adventure, Sci-Fi",Marc Webb,"Andrew Garfield, Emma Stone, Rhys Ifans",...,NaN,1,Spider-Man,527900000,2.30,7,Tuesday,14,USA,50000000
96,97,The Hunger Games: Mockingjay - Part 1,Lionsgate,$755.40,2014,125000000.0,123.0,"Adventure, Sci-Fi, Thriller",Francis Lawrence,"Jennifer Lawrence, Josh Hutcherson, Liam Hemsw...",...,NaN,1,Hunger Games,630400000,5.04,11,Friday,12,USA,50000000
97,98,Shrek Forever After,Dreamworks,$752.60,2010,165000000.0,93.0,"Animation, Adventure, Comedy",Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz",...,NaN,1,Shrek,587600000,3.56,5,Friday,16,USA,40000000
98,99,X-Men: Days of Future Past,Fox,$747.90,2014,200000000.0,132.0,"Action, Adventure, Sci-Fi",Bryan Singer,"Hugh Jackman, James McAvoy, Michael Fassbender",...,NaN,1,X-Men,547900000,2.74,5,Friday,12,USA,60000000
99,100,Madagascar 3: Europe's Most Wanted,Dreamworks,$746.90,2012,145000000.0,93.0,"Animation, Adventure, Comedy",Eric Darnell,"Ben Stiller, Chris Rock, David Schwimmer",...,NaN,1,Madagascar,601900000,4.15,6,Friday,14,USA,50000000

In [7]:
movies = pd.read_csv("movies-new.csv")
movies

,Rank,Title,Studio,Gross,Year,Budget,Runtime,Genre,Director,Actors,...,Awards,Sequel,Franchise,Profit,ROI,ReleaseMonth,ReleaseDayOfWeek,Age,ProductionCountries,WeekendGross
0,1,Avengers: Endgame,Buena Vista,"$2,796.30",2019,356000000.0,181.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Evans, Mark Ruffalo",...,Oscar for Best Visual Effects,1,Marvel,2440300000,6.85,4,Friday,7,USA,150000000
1,2,Avatar,Fox,"$2,789.70",2009,237000000.0,162.0,"Action, Adventure, Fantasy",James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver",...,Oscar for Best Cinematography,0,NaN,2522700000,10.64,12,Friday,17,USA,180000000
2,3,Titanic,Paramount,"$2,187.50",1997,200000000.0,195.0,"Drama, Romance",James Cameron,"Leonardo DiCaprio, Kate Winslet, Billy Zane",...,Oscar for Best Picture,0,NaN,1987500000,9.94,12,Friday,29,USA,120000000
3,4,Star Wars: The Force Awakens,Buena Vista,"$2,068.20",2015,245000000.0,138.0,"Action, Adventure, Sci-Fi",J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac",...,NaN,1,Star Wars,1823200000,7.44,12,Friday,11,USA,170000000
4,5,Avengers: Infinity War,BV,"$2,048.40",2018,300000000.0,149.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Hemsworth, Josh Brolin",...,NaN,1,Marvel,1748400000,5.83,4,Friday,8,USA,190000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,The Amazing Spider-Man,Sony,$757.90,2012,230000000.0,136.0,"Action, Adventure, Sci-Fi",Marc Webb,"Andrew Garfield, Emma Stone, Rhys Ifans",...,NaN,1,Spider-Man,527900000,2.30,7,Tuesday,14,USA,50000000
96,97,The Hunger Games: Mockingjay - Part 1,Lionsgate,$755.40,2014,125000000.0,123.0,"Adventure, Sci-Fi, Thriller",Francis Lawrence,"Jennifer Lawrence, Josh Hutcherson, Liam Hemsw...",...,NaN,1,Hunger Games,630400000,5.04,11,Friday,12,USA,50000000
97,98,Shrek Forever After,Dreamworks,$752.60,2010,165000000.0,93.0,"Animation, Adventure, Comedy",Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz",...,NaN,1,Shrek,587600000,3.56,5,Friday,16,USA,40000000
98,99,X-Men: Days of Future Past,Fox,$747.90,2014,200000000.0,132.0,"Action, Adventure, Sci-Fi",Bryan Singer,"Hugh Jackman, James McAvoy, Michael Fassbender",...,NaN,1,X-Men,547900000,2.74,5,Friday,12,USA,60000000
99,100,Madagascar 3: Europe's Most Wanted,Dreamworks,$746.90,2012,145000000.0,93.0,"Animation, Adventure, Comedy",Eric Darnell,"Ben Stiller, Chris Rock, David Schwimmer",...,NaN,1,Madagascar,601900000,4.15,6,Friday,14,USA,50000000

In [8]:
# head(n) method of dataframe to display first n rows, default value is 5

In [9]:
movies.head()

,Rank,Title,Studio,Gross,Year,Budget,Runtime,Genre,Director,Actors,...,Awards,Sequel,Franchise,Profit,ROI,ReleaseMonth,ReleaseDayOfWeek,Age,ProductionCountries,WeekendGross
0,1,Avengers: Endgame,Buena Vista,"$2,796.30",2019,356000000.0,181.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Evans, Mark Ruffalo",...,Oscar for Best Visual Effects,1,Marvel,2440300000,6.85,4,Friday,7,USA,150000000
1,2,Avatar,Fox,"$2,789.70",2009,237000000.0,162.0,"Action, Adventure, Fantasy",James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver",...,Oscar for Best Cinematography,0,NaN,2522700000,10.64,12,Friday,17,USA,180000000
2,3,Titanic,Paramount,"$2,187.50",1997,200000000.0,195.0,"Drama, Romance",James Cameron,"Leonardo DiCaprio, Kate Winslet, Billy Zane",...,Oscar for Best Picture,0,NaN,1987500000,9.94,12,Friday,29,USA,120000000
3,4,Star Wars: The Force Awakens,Buena Vista,"$2,068.20",2015,245000000.0,138.0,"Action, Adventure, Sci-Fi",J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac",...,NaN,1,Star Wars,1823200000,7.44,12,Friday,11,USA,170000000
4,5,Avengers: Infinity War,BV,"$2,048.40",2018,300000000.0,149.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Hemsworth, Josh Brolin",...,NaN,1,Marvel,1748400000,5.83,4,Friday,8,USA,190000000

In [10]:
type(movies)  # data type of the object

pandas.core.frame.DataFrame

In [11]:
movies.head(2)

,Rank,Title,Studio,Gross,Year,Budget,Runtime,Genre,Director,Actors,...,Awards,Sequel,Franchise,Profit,ROI,ReleaseMonth,ReleaseDayOfWeek,Age,ProductionCountries,WeekendGross
0,1,Avengers: Endgame,Buena Vista,"$2,796.30",2019,356000000.0,181.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Evans, Mark Ruffalo",...,Oscar for Best Visual Effects,1,Marvel,2440300000,6.85,4,Friday,7,USA,150000000
1,2,Avatar,Fox,"$2,789.70",2009,237000000.0,162.0,"Action, Adventure, Fantasy",James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver",...,Oscar for Best Cinematography,0,NaN,2522700000,10.64,12,Friday,17,USA,180000000

- **Important observation**: The 'Gross' column contains a $ sign and a trailing space - this means it is a **string**, not a number. **Data Analysis always starts with noticing such issues**.

### Step 3: Check the shape and column names

In [12]:
print("Number of rows and columns:", movies.shape)
print("\nColumn names:")
print(movies.columns.tolist())

Number of rows and columns: (100, 27)

Column names:
['Rank', 'Title', 'Studio', 'Gross', 'Year', 'Budget', 'Runtime', 'Genre', 'Director', 'Actors', 'ReleaseDate', 'Country', 'Language', 'Rating', 'Votes', 'Metascore', 'MPAA', 'Awards', 'Sequel', 'Franchise', 'Profit', 'ROI', 'ReleaseMonth', 'ReleaseDayOfWeek', 'Age', 'ProductionCountries', 'WeekendGross']

### Step 4: Get a comprehensive summary with `info()`

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rank                 100 non-null    int64
 1   Title                100 non-null    object
 2   Studio               100 non-null    object
 3   Gross                100 non-null    object
 4   Year                 100 non-null    int64
 5   Budget               99 non-null     float64
 6   Runtime              99 non-null     float64
 7   Genre                100 non-null    object
 8   Director             100 non-null    object
 9   Actors               100 non-null    object
 10  ReleaseDate          100 non-null    object
 11  Country              100 non-null    object
 12  Language             100 non-null    object
 13  Rating               99 non-null     float64
 14  Votes                100 non-null    int64
 15  Metascore            100 non-null    int64
 16  MPAA                 99 non-null     object
 17  Awards               20 non-null     object
 18  Sequel               100 non-null    int64
 19  Franchise            79 non-null     object
 20  Profit               100 non-null    int64
 21  ROI                  100 non-null    float64
 22  ReleaseMonth         100 non-null    int64
 23  ReleaseDayOfWeek     100 non-null    object
 24  Age                  100 non-null    int64
 25  ProductionCountries  100 non-null    object
 26  WeekendGross         100 non-null    int64
dtypes: float64(4), int64(9), object(14)
memory usage: 21.2+ KB

##### What `.info()` tell us
- **Not-Null Count**
- **Dtype**
- **Memory usage**
- **Immediate red flags**: Convert the columns to proper Dtype

### Step 5: Numerical Summary with `.describe()`

In [16]:
movies.describe()  # descriptive statistics

,Rank,Year,Budget,Runtime,Rating,Votes,Metascore,Sequel,Profit,ROI,ReleaseMonth,Age,WeekendGross
count,100.000000,100.00000,9.900000e+01,99.000000,99.000000,1.000000e+02,100.000000,100.000000,1.000000e+02,100.000000,100.000000,100.00000,1.000000e+02
mean,50.500000,2010.88000,1.607525e+08,132.040404,7.374747,6.841000e+05,67.050000,0.760000,8.695060e+08,7.283900,7.170000,15.12000,7.680000e+07
std,29.011492,7.52676,6.956954e+07,24.852594,0.849891,4.217810e+05,14.870739,0.429235,3.638395e+08,10.629655,2.923451,7.52676,3.434466e+07
min,1.000000,1977.00000,-5.000000e+07,87.000000,5.500000,2.000000e+05,32.000000,0.000000,-2.000000e+08,-25.300000,2.000000,7.00000,3.000000e+07
25%,25.750000,2007.75000,1.150000e+08,116.500000,6.800000,4.275000e+05,57.500000,1.000000,6.679500e+08,3.707500,5.000000,10.00000,5.000000e+07
50%,50.500000,2013.00000,1.700000e+08,133.000000,7.400000,6.000000e+05,66.000000,1.000000,7.936500e+08,5.100000,6.000000,13.00000,7.000000e+07
75%,75.250000,2016.00000,2.000000e+08,148.000000,7.900000,7.725000e+05,77.250000,1.000000,9.248250e+08,7.825000,11.000000,18.25000,9.000000e+07
max,100.000000,2019.00000,3.560000e+08,201.000000,11.000000,2.700000e+06,105.000000,1.000000,2.522700e+09,74.510000,12.000000,49.00000,1.900000e+08

##### **Key Statistics**
- **Count** - Number of non-missing values
- **Mean vs Median (50%)** - If they differ, the distribution is skewed
- **Min/Max** - identify extreme values
- **Std** - standard deviation; larger means more spread
---
**NOTE**: `describe()` automatically excludes *object* columns. To see the summary for categorical columns, we use `.describe(include='object')`

In [18]:
movies.describe(include='object')

,Title,Studio,Gross,Genre,Director,Actors,ReleaseDate,Country,Language,MPAA,Awards,Franchise,ReleaseDayOfWeek,ProductionCountries
count,100,100,100,100,100,100,100,100,100,99,20,79,100,100
unique,100,11,99,22,64,82,100,2,2,4,9,28,5,2
top,Avengers: Endgame,Buena Vista,$880.20,"Action, Adventure, Sci-Fi",Peter Jackson,"Daniel Radcliffe, Emma Watson, Rupert Grint",2019-04-26,USA,English,PG-13,Oscar for Best Visual Effects,Marvel,Friday,USA
freq,1,31,2,33,6,8,1,99,99,66,7,11,77,99

### Step 6: Check the first and last few rows with `.head()` and `.tail()`

In [20]:
movies.head(10) # First 10 rows

,Rank,Title,Studio,Gross,Year,Budget,Runtime,Genre,Director,Actors,...,Awards,Sequel,Franchise,Profit,ROI,ReleaseMonth,ReleaseDayOfWeek,Age,ProductionCountries,WeekendGross
0,1,Avengers: Endgame,Buena Vista,"$2,796.30",2019,356000000.0,181.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Evans, Mark Ruffalo",...,Oscar for Best Visual Effects,1,Marvel,2440300000,6.85,4,Friday,7,USA,150000000
1,2,Avatar,Fox,"$2,789.70",2009,237000000.0,162.0,"Action, Adventure, Fantasy",James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver",...,Oscar for Best Cinematography,0,NaN,2522700000,10.64,12,Friday,17,USA,180000000
2,3,Titanic,Paramount,"$2,187.50",1997,200000000.0,195.0,"Drama, Romance",James Cameron,"Leonardo DiCaprio, Kate Winslet, Billy Zane",...,Oscar for Best Picture,0,NaN,1987500000,9.94,12,Friday,29,USA,120000000
3,4,Star Wars: The Force Awakens,Buena Vista,"$2,068.20",2015,245000000.0,138.0,"Action, Adventure, Sci-Fi",J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac",...,NaN,1,Star Wars,1823200000,7.44,12,Friday,11,USA,170000000
4,5,Avengers: Infinity War,BV,"$2,048.40",2018,300000000.0,149.0,"Action, Adventure, Sci-Fi",Anthony Russo,"Robert Downey Jr., Chris Hemsworth, Josh Brolin",...,NaN,1,Marvel,1748400000,5.83,4,Friday,8,USA,190000000
5,6,Jurassic World,Universal,"$1,671.70",2015,NaN,124.0,"Action, Adventure, Sci-Fi",Colin Trevorrow,"Chris Pratt, Bryce Dallas Howard",...,NaN,1,Jurassic Park,1521700000,10.14,6,Friday,11,USA,140000000
6,7,Marvel's The Avengers,Buena Vista,"$1,518.80",2012,220000000.0,143.0,"Action, Adventure, Sci-Fi",Joss Whedon,"Robert Downey Jr., Chris Evans, Scarlett Johan...",...,NaN,1,Marvel,1298800000,5.90,5,Friday,14,USA,160000000
7,8,Furious 7,Universal,"$1,516.00",2015,190000000.0,137.0,"Action, Crime, Thriller",James Wan,"Vin Diesel, Paul Walker, Dwayne Johnson",...,NaN,1,Fast & Furious,1326000000,6.98,4,Friday,11,USA,130000000
8,9,Avengers: Age of Ultron,Buena Vista,"$1,405.40",2015,280000000.0,141.0,"Action, Adventure, Sci-Fi",Joss Whedon,"Robert Downey Jr., Chris Hemsworth",...,NaN,1,Marvel,1125400000,4.02,5,Friday,11,USA,150000000
9,10,Black Panther,Buena Vista,"$1,346.90",2018,200000000.0,NaN,"Action, Adventure, Sci-Fi",Ryan Coogler,"Chadwick Boseman, Michael B. Jordan, Lupita Ny...",...,Oscar for Best Costume Design,1,Marvel,1146900000,5.73,2,Friday,8,USA,110000000

In [21]:
movies.tail(5)   # Last 5 rows

,Rank,Title,Studio,Gross,Year,Budget,Runtime,Genre,Director,Actors,...,Awards,Sequel,Franchise,Profit,ROI,ReleaseMonth,ReleaseDayOfWeek,Age,ProductionCountries,WeekendGross
95,96,The Amazing Spider-Man,Sony,$757.90,2012,230000000.0,136.0,"Action, Adventure, Sci-Fi",Marc Webb,"Andrew Garfield, Emma Stone, Rhys Ifans",...,NaN,1,Spider-Man,527900000,2.30,7,Tuesday,14,USA,50000000
96,97,The Hunger Games: Mockingjay - Part 1,Lionsgate,$755.40,2014,125000000.0,123.0,"Adventure, Sci-Fi, Thriller",Francis Lawrence,"Jennifer Lawrence, Josh Hutcherson, Liam Hemsw...",...,NaN,1,Hunger Games,630400000,5.04,11,Friday,12,USA,50000000
97,98,Shrek Forever After,Dreamworks,$752.60,2010,165000000.0,93.0,"Animation, Adventure, Comedy",Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz",...,NaN,1,Shrek,587600000,3.56,5,Friday,16,USA,40000000
98,99,X-Men: Days of Future Past,Fox,$747.90,2014,200000000.0,132.0,"Action, Adventure, Sci-Fi",Bryan Singer,"Hugh Jackman, James McAvoy, Michael Fassbender",...,NaN,1,X-Men,547900000,2.74,5,Friday,12,USA,60000000
99,100,Madagascar 3: Europe's Most Wanted,Dreamworks,$746.90,2012,145000000.0,93.0,"Animation, Adventure, Comedy",Eric Darnell,"Ben Stiller, Chris Rock, David Schwimmer",...,NaN,1,Madagascar,601900000,4.15,6,Friday,14,USA,50000000

- **Why view tail?** Sometimes data is sorted in a spcific order; looking at the end helps confirm that the dataset covers the entire top-100 list correctly.

### Step 7: Quick check for missing values

In [22]:
# Count missing values per column
movies.isnull().sum()

Rank                    0
Title                   0
Studio                  0
Gross                   0
Year                    0
Budget                  1
Runtime                 1
Genre                   0
Director                0
Actors                  0
ReleaseDate             0
Country                 0
Language                0
Rating                  1
Votes                   0
Metascore               0
MPAA                    1
Awards                 80
Sequel                  0
Franchise              21
Profit                  0
ROI                     0
ReleaseMonth            0
ReleaseDayOfWeek        0
Age                     0
ProductionCountries     0
WeekendGross            0
dtype: int64

### Step 8: Check the data types of each column

In [23]:
movies.dtypes

Rank                     int64
Title                   object
Studio                  object
Gross                   object
Year                     int64
Budget                 float64
Runtime                float64
Genre                   object
Director                object
Actors                  object
ReleaseDate             object
Country                 object
Language                object
Rating                 float64
Votes                    int64
Metascore                int64
MPAA                    object
Awards                  object
Sequel                   int64
Franchise               object
Profit                   int64
ROI                    float64
ReleaseMonth             int64
ReleaseDayOfWeek        object
Age                      int64
ProductionCountries     object
WeekendGross             int64
dtype: object

### Step 9: Quick data exploration - Unique values in categorical columns

In [24]:
# from movies dataframe - we can extract a column in two ways
# dataframe.column
# datafrom[column]

In [27]:
movies.Title   # movies.Studio

0                         Avengers: Endgame
1                                    Avatar
2                                   Titanic
3              Star Wars: The Force Awakens
4                    Avengers: Infinity War
                      ...
95                   The Amazing Spider-Man
96    The Hunger Games: Mockingjay - Part 1
97                      Shrek Forever After
98               X-Men: Days of Future Past
99       Madagascar 3: Europe's Most Wanted
Name: Title, Length: 100, dtype: object

In [28]:
movies["Studio"]   # movies["Title"]

0     Buena Vista
1             Fox
2       Paramount
3     Buena Vista
4              BV
         ...
95           Sony
96      Lionsgate
97     Dreamworks
98            Fox
99     Dreamworks
Name: Studio, Length: 100, dtype: object

In [29]:
print("Unique Studios:", movies['Studio'].unique())

Unique Studios: ['Buena Vista' 'Fox' 'Paramount' 'BV' 'Universal' 'Warner Brothers'
 'New Line' 'Sony' 'Dreamworks' 'HC' 'Lionsgate']

In [30]:
print("Unique MPAA ratings:", movies["MPAA"].unique())

Unique MPAA ratings: ['PG-13' 'PG' nan 'G' 'R']

In [31]:
print("Unique Languages:", movies['Language'].unique())

Unique Languages: ['English' 'Mandarin']

- **Why this matters?** Knowing the unique values helps to decide how to encode, group, or filter data later.

### Step 10: Memory usage

In [32]:
print("Memory usage (in MB):", movies.memory_usage(deep=True).sum() / 1024**2)

Memory usage (in MB): 0.0996847152709961

(This is tiny, but in real datasets memory is crucial.)

#### Golden rule:
- Always run `.info()` and `.describe()` as soon as you load new data - they give you 80% of what you need to know before doing any analysis.

### Assignment

##### Task 1 (Basic):
- Create a new DataFrame called last_20 that contains the last 20 rows of movies. Print the shape, column names, and the .info() summary of this subset.

##### Task 2 (Intermediate):
Using movies.describe(include='object') answer these questions:
- Which studio appears most frequently? How many times?
- Which MPAA rating is the least common?
- How many unique directors are there?

##### Task 3 (Advanced – thinking about data quality):
Using movies.isnull().sum():

- Write a sentence explaining why Franchise might have 22 missing values. Is it truly missing, or is it "not applicable"?
- Look at the row with the missing Budget. Using movies[movies['Budget'].isna()], print that entire row. What movie is it? (Hint: it's one of the top 100). Why do you think its budget is missing?

##### Task 4 (Python practice):
Write a loop that iterates over all columns and prints the column name and its data type, but only if the data type is 'object'. (Use for col in movies.columns:)

##### Task 4:
Check the correlation between Votes and Metascore using movies[['Votes','Metascore']].corr(). What does the result tell you? (We'll cover correlation deeply in Session 13, but try it now.)