# 3. Data Types & Basic Statistics

## Key Concepts
### 1. Data Type Conversion
- `pd.to_numeric()` - converts a Series to numeric, handling error (e.g., `coerce` for invalid entries)
- `pd.to_datetime()` converts a Series to datetime objects
- `.astype()` - used for simple type changes (e.g., `float` or `int`)
### 2. Why Convert?
- Math operations (like subtraction for `Profit`) require numbers, not strings
- Time-series analysis requires datetime objects
- Visualizations and statistical functions expect proper data types
### 3. Descriptive Statistics
- **Mean** - arithmetic average ( sum / count ). Sensitive to outliers.
- **Meidan** - middle value (50th percentile). Robust to outliers.
- **Mode** - most frequent value. Used for categorical data (or descrete numeric).
- **Standard Deviation** (`std`) - measure of spread around the mean.
- **Quantiles** - cut points dividing the data into intervalues (e.g., 25%, 50%, 75%). The **Interquartile Range (IQR)** = 75% - 25%.

### Step 0: Load the cleaned dataset

- Open your notebook and load the file you saved

In [1]:
import pandas as pd
import numpy as np
movies = pd.read_csv("movies_cleaned.csv")

# Double-check that no missing values remain
print(movies.isnull().sum().sum()) # Should be 0
print(movies.dtypes)

81
Rank                     int64
Title                   object
Studio                  object
Gross                   object
Year                     int64
Budget                 float64
Runtime                float64
Genre                   object
Director                object
Actors                  object
ReleaseDate             object
Country                 object
Language                object
Rating                 float64
Votes                    int64
Metascore                int64
MPAA                    object
Awards                  object
Sequel                   int64
Franchise               object
ReleaseMonth             int64
ReleaseDayOfWeek        object
Age                      int64
ProductionCountries     object
WeekendGross             int64
dtype: object

In [2]:
movies.isnull().sum().sum()

81

- **Observation**: `Gross` and 1ReleaseDate` are still object (strings). We will fix them now.

### Step 1: Convert `Gross` to numeric (in millions)

- Important: The original `Gross` is in **millions** (e.g., "`$2,796.30`" = 2,796,30 million dollars).
- We will convert `Gross` to **raw dollars** (multiply by 1,000,000) so that `Profit` calculations match the original dataset's scale.

In [3]:
# Clean Gross: remove '$', commas, spaces, convert to float, then multiply by 1000000
movies["Gross"] = movies["Gross"].astype(str).str.replace("$", "")
movies["Gross"]

0     2,796.30
1     2,789.70
2     2,187.50
3     2,068.20
4     2,048.40
        ...
95      757.90
96      755.40
97      752.60
98      747.90
99      746.90
Name: Gross, Length: 100, dtype: object

In [4]:
movies["Gross"] = movies["Gross"].str.replace(",", "")
movies["Gross"]

0     2796.30
1     2789.70
2     2187.50
3     2068.20
4     2048.40
        ...
95     757.90
96     755.40
97     752.60
98     747.90
99     746.90
Name: Gross, Length: 100, dtype: object

In [5]:
movies["Gross"] = movies["Gross"].str.strip()
movies["Gross"]

0     2796.30
1     2789.70
2     2187.50
3     2068.20
4     2048.40
       ...
95     757.90
96     755.40
97     752.60
98     747.90
99     746.90
Name: Gross, Length: 100, dtype: object

In [6]:
movies["Gross"] = pd.to_numeric(movies["Gross"]) * 1_000_000
movies["Gross"]

0     2.796300e+09
1     2.789700e+09
2     2.187500e+09
3     2.068200e+09
4     2.048400e+09
          ...
95    7.579000e+08
96    7.554000e+08
97    7.526000e+08
98    7.479000e+08
99    7.469000e+08
Name: Gross, Length: 100, dtype: float64

In [7]:
movies[["Title", "Gross", "WeekendGross"]].head(3)

               Title         Gross  WeekendGross
0  Avengers: Endgame  2.796300e+09     150000000
1             Avatar  2.789700e+09     180000000
2            Titanic  2.187500e+09     120000000

- **Why multiply by 1,000,000?** The original `Profit` column had values like 2847000000 (dollars). To recalculate `Profit` correctly, we need `Gross` in raw dollars.

### Step 2: Convert `ReleaseDate` to datetime

In [8]:
movies['ReleaseDate'] = pd.to_datetime(movies['ReleaseDate'])

# Check the data type
print(movies['ReleaseDate'].dtype)
# Should be datetime64[ns]
print(movies['ReleaseDate'].head(3))

datetime64[ns]
0   2019-04-26
1   2009-12-18
2   1997-12-19
Name: ReleaseDate, dtype: datetime64[ns]

- Note: We can now extract the exact weekday name or month name easily.

### Step 3: Recalculate `Profit` and `ROI`

- Now, the `Gross` and `Budget` are numeric, let's `Profit` and `ROI` columns

In [9]:
# Profit = Gross - Budget
movies['Profit'] = movies['Gross'] - movies['Budget']

# ROI = Profit / Budget (as a ratio, not percentage)
movies['ROI'] = movies['Profit'] / movies['Budget']

# Check first 5
movies[["Title", "Budget", "Gross", "Profit", "ROI"]].head()

,Title,Budget,Gross,Profit,ROI
0,Avengers: Endgame,356000000.0,2.796300e+09,2.440300e+09,6.854775
1,Avatar,237000000.0,2.789700e+09,2.552700e+09,10.770886
2,Titanic,200000000.0,2.187500e+09,1.987500e+09,9.937500
3,Star Wars: The Force Awakens,245000000.0,2.068200e+09,1.823200e+09,7.441633
4,Avengers: Infinity War,300000000.0,2.048400e+09,1.748400e+09,5.828000

### Step 4: Verify all data types after conversion

In [10]:
movies.dtypes

Rank                            int64
Title                          object
Studio                         object
Gross                         float64
Year                            int64
Budget                        float64
Runtime                       float64
Genre                          object
Director                       object
Actors                         object
ReleaseDate            datetime64[ns]
Country                        object
Language                       object
Rating                        float64
Votes                           int64
Metascore                       int64
MPAA                           object
Awards                         object
Sequel                          int64
Franchise                      object
ReleaseMonth                    int64
ReleaseDayOfWeek               object
Age                             int64
ProductionCountries            object
WeekendGross                    int64
Profit                        float64
ROI                           float64
dtype: object

- All numeric columns are now proper numbers! We are ready for full statitical analysis.

### Step 5: Use `.describe()` for a complete numeric summary

In [11]:
movies.describe()

,Rank,Gross,Year,Budget,Runtime,ReleaseDate,Rating,Votes,Metascore,Sequel,ReleaseMonth,Age,WeekendGross,Profit,ROI
count,100.000000,1.000000e+02,100.00000,1.000000e+02,100.000000,100,100.000000,1.000000e+02,100.000000,100.000000,100.000000,100.00000,1.000000e+02,1.000000e+02,100.000000
mean,50.500000,1.041537e+09,2010.88000,1.607525e+08,132.040404,2011-06-07 20:09:36,7.375000,6.841000e+05,67.050000,0.760000,7.170000,15.12000,7.680000e+07,8.807845e+08,7.333978
min,1.000000,7.469000e+08,1977.00000,-5.000000e+07,87.000000,1977-05-25 00:00:00,5.500000,2.000000e+05,32.000000,0.000000,2.000000,7.00000,3.000000e+07,5.279000e+08,-25.296000
25%,25.750000,8.266750e+08,2007.75000,1.150000e+08,117.250000,2008-03-04 00:00:00,6.800000,4.275000e+05,57.500000,1.000000,5.000000,10.00000,5.000000e+07,6.709250e+08,3.743000
50%,50.500000,9.372500e+08,2013.00000,1.675000e+08,133.000000,2013-06-13 00:00:00,7.400000,6.000000e+05,66.000000,1.000000,6.000000,13.00000,7.000000e+07,7.962000e+08,5.097800
75%,75.250000,1.105225e+09,2016.00000,2.000000e+08,148.000000,2016-11-25 00:00:00,7.900000,7.725000e+05,77.250000,1.000000,11.000000,18.25000,9.000000e+07,9.248250e+08,7.826609
max,100.000000,2.796300e+09,2019.00000,3.560000e+08,201.000000,2019-05-24 00:00:00,11.000000,2.700000e+06,105.000000,1.000000,12.000000,49.00000,1.900000e+08,2.552700e+09,74.514286
std,29.011492,3.704681e+08,7.52676,6.921728e+07,24.726757,NaN,0.845592,4.217810e+05,14.870739,0.429235,2.923451,7.52676,3.434466e+07,3.486871e+08,10.599267

#### Key insights from `.describe()`:
- **Gross** - mean > median, the distribution is **right-skewed**
- **ROI** - mean > median, the distribution is **right-skewed**
- **Age** - mean > median, the distribution is **right-skewed**

### Step 6: Calculate specific statistics manually (for deeper understanding)

In [12]:
gross_mean = movies["Gross"].mean()
gross_median = movies["Gross"].median()
gross_std = movies["Gross"].std()
gross_quantiles = movies["Gross"].quantile([0.25, 0.50, 0.75])

print("Gross Mean:", gross_mean)
print("Gross Median:", gross_median)
print("Gross Std:", gross_std)
print("Gross Quantiles:", gross_quantiles)

Gross Mean: 1041537000.0
Gross Median: 937250000.0
Gross Std: 370468065.84251076
Gross Quantiles: 0.25    8.266750e+08
0.50    9.372500e+08
0.75    1.105225e+09
Name: Gross, dtype: float64

- **Interpretation**: The IQR = 75% - 25%. This tells us the middle 50% of movies have grosses that differ.

### Step 7: Calculate Mode

`.mode()` returns the most frequent value(s). For numeric columns, if there are multiple, it returns all.

In [13]:
movies['Sequel']

0     1
1     0
2     0
3     1
4     1
     ..
95    1
96    1
97    1
98    1
99    1
Name: Sequel, Length: 100, dtype: int64

In [14]:
# Mode of 'Sequel' (0 or 1)
print("Mode of sequel:", movies['Sequel'].mode())

Mode of sequel: 0    1
Name: Sequel, dtype: int64

In [15]:
# Mode of `Rating` (since it's numeric)
print("Mode of Rating:", movies['Rating'].mode())

Mode of Rating: 0    7.4
Name: Rating, dtype: float64

In [16]:
# Mode of categorical column 'MPAA'
print("Mode of MPAA", movies["MPAA"].mode())

Mode of MPAA 0    PG-13
Name: MPAA, dtype: object

In [17]:
print(movies["MPAA"].tolist())

['PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG', 'PG', 'PG', 'PG-13', 'PG-13', 'PG', nan, 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'G', 'PG-13', 'PG-13', 'PG-13', 'PG', 'PG-13', 'PG', 'PG', 'PG', 'PG', 'PG-13', 'PG-13', 'PG', 'PG', 'G', 'PG', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'G', 'PG-13', 'PG-13', 'PG-13', 'PG', 'PG-13', 'PG-13', 'PG-13', 'PG', 'PG-13', 'PG', 'PG-13', 'PG', 'PG', 'PG', 'PG-13', 'PG-13', 'R', 'PG-13', 'PG-13', 'PG', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG', 'PG', 'PG', 'PG-13', 'PG', 'PG-13', 'PG-13', 'PG-13', 'R', 'PG-13', 'R', 'PG', 'PG-13', 'PG-13', 'PG', 'PG-13', 'PG-13', 'PG-13', 'PG', 'PG-13', 'PG']

##### Interesting
- `Sequel` has **two modies** (0 and 1) - meaning equal of non-sequals and sequals (50/50)
- `Rating` mode is 7.4 (which matches the median
- `MPAA` mode is PG-13 (most common rating)

### Step 8: Understand skewness with mean vs median

- Right-skewed: mean > median
- Left-skewed: mean < median
- Symmetric: mean = median

In [18]:
cols = ["Gross", "Budget", "ROI", "Runtime", "Votes"]
for col in cols:
    mean_val = movies[col].mean()
    median_val = movies[col].median()
    skew = "Right-skewed" if mean_val > median_val else "Left-skewed" if mean_val < median_val else "Symmetric"
    print(col + " | " + "Mean: " + str(mean_val) + " | " + str(median_val) + " | " + str(skew))

Gross | Mean: 1041537000.0 | 937250000.0 | Right-skewed
Budget | Mean: 160752525.25252524 | 167500000.0 | Left-skewed
ROI | Mean: 7.333978403298065 | 5.097799999999999 | Right-skewed
Runtime | Mean: 132.04040404040404 | 133.0 | Left-skewed
Votes | Mean: 684100.0 | 600000.0 | Right-skewed

- **Why it matters**: Right-skew means a few high-value outliers pull the mean up. When reporting averages, **median** is often a better summary for skewed data.

### Step 9: Quantile practice - find the 90th percentile

- You might want to know: "What gross is required to be in the top 10%?"

In [20]:
top_10_percent_gross = movies['Gross'].quantile(0.90)

In [21]:
print("90th percentile gross:", top_10_percent_gross)

90th percentile gross: 1342220000.0

In [23]:
# Count how many movies exceed this
(movies['Gross'] > top_10_percent_gross).sum()

10

### Step 10: Save the fully cleaned and typed dataset

In [24]:
movies.to_csv('movies_final.csv', index=False)
print("Fully cleaned dataset saved as 'movies_final.csv'")

Fully cleaned dataset saved as 'movies_final.csv'

### Summary

- **Converting messy strings** to numeric (removing `$`, commas) and datatime.
- **Recalculating derived metrics** (Profit, ROI) using vectorized operations.
- **Computing and interpreting** mean, median, mode, standard deviation, and quantiles.
- **Detecting skewness** by comparing mean and median.
- **Using** .quantile() to find percentiles and identify top/bottom tiers.

- **Golden rule:** Always check data types before analysis. If a column is `object`, it's almost certainly not ready for math or time-series operations. Convert it **before** you compute any statistics.